layout: post
title: Erain's repos
subtitle: Erain's sub-repos
tags: welcoming
description: Erian is learning
theme: jekyll-theme-minimal
comments: true
name: Erain's Workspace

deploy:
 type: git
 repo: git@github.com:ys11i0123/ys11i0123.github.io.git
 branch: main

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true


github: https://github.com/Erain-997
email: https://mail.qq.com/
weibo: https://weibo.com/n/Lemon%E4%B8%B6Damon

rss: true

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock